name: Obfuscate and Commit

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  obfuscate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Fix permissions for obfuscator
        run: chmod +x node_modules/.bin/javascript-obfuscator || true
      - name: Run obfuscation build (robust)
        run: |
          node node_modules/javascript-obfuscator/bin/javascript-obfuscator.js src/index.js --output src/index.obf.js || echo "Obfuscation step failed, continuing..."
      - name: Upload obfuscated file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: obfuscated-js
          path: src/index.obf.js
